### ISSUE TITLE
Container hang when running [bash] or [/bin/bash] instead of bash or /bin/bash

### ISSUE THREAD

**Issue by lilianmoraru** [tailhook/vagga#112]
Vagga version: v0.4.0-54-g331f7f0

The configuration file:
```
containers:
  ubuntu:
    setup:
    - !UbuntuRelease { version: 15.10 }

commands:
  ubuntu: !Command
    container: ubuntu
    run: [/bin/bash]
```

When trying to `exit`, the container will hang and you have to go and kill vagga from another terminal.
Replacing `run: [/bin/bash]` with `run: /bin/bash` solves the issue.
My guess is that this could be replicated with other commands too.
