### ISSUE TITLE
Pip with subcontainers fails in 0.4.1

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#113]
Example:
```
containers:
  ubuntu:
    setup:
    - !UbuntuRelease { version: 15.04 }
    - !Py3Install [aioredis]
  broken:
    setup:
    - !Container ubuntu
```
