### ISSUE TITLE
performance regression

### ISSUE THREAD

**Issue by popravich** [tailhook/vagga#117]
After update to latest testing version `!Container` command is terribly slow.
Tested several times, with and without cache.

config:
```yaml
containers:
  ubuntu1:
    setup:
    - !Ubuntu trusty
  ubuntu2:
    setup:
    - !Container ubuntu1
```
Running vagga `v0.4.1-1-g78b5712-1`:
ubuntu1 timings.log:
```
  0.000   0.000   Start 1446844471.876842
  0.000   0.000   Prepare
  2.877   2.877   Step: Ubuntu("trusty")
  3.356   0.478   Finish
```
ubuntu2 timings.log:
```
  0.000   0.000   Start 1446844475.499925
  0.000   0.000   Prepare
  0.346   0.346   Step: Container("ubuntu1")
  0.757   0.411   Finish
```

Running vagga `v0.4.1-5-g978c931-1`
ubuntu1 timings.log
```
  0.000   0.000   Start 1446845540.264276
  0.004   0.004   Prepare
  2.923   2.919   Step: Ubuntu("trusty")
  3.388   0.466   Finish
```
ubuntu2 timings.log
```
  0.000   0.000   Start 1446845543.896893
  0.004   0.004   Prepare
 36.112  36.109   Step: Container("ubuntu1")
 36.424   0.311   Finish
```
