### ISSUE TITLE
Cleanup environment of vagga container

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#122]
The following environment variables are used internally and should not be propagated to the real container:

1. `VAGGA_USER_HOME`
2. `HOST_PATH`
3. `PWD`

They should have better naming convention, probably `VAGGA_` or `_VAGGA_` (to endorse that they are internal), and be cleaned when running user process (they are used to propagate information between vagga processes internally)

**Comment by lilianmoraru** [comment]
Here is a simple config file that can replicate the issue:
```yaml
containers:
  alpine:
    setup:
    - !Alpine v3.2
    - !EnsureDir /test_vagga

    volumes:
      /test_vagga: !BindRW /volumes/test_vagga
    
commands:
  test: !Command
    description:    "Test issue#122 @link: https://github.com/tailhook/vagga/issues/122"
    container:      alpine
    work-dir:       /test_vagga
    run:            set -ex; if [ "$(pwd)" != "$(readlink /proc/self/cwd)" ]; then echo "Test failed"; else echo "Test passed"; fi
```

And a messy bash script that should be put in to the same folder with `vagga.yaml`:
```sh
#! /bin/bash

main() {
  ## Just a temp folder that we will also use in vagga.yaml
  local temp_folder="$HOME/test_vagga_issue_122"
  mkdir -p "$temp_folder"

  ## vagga settings to configure an external volume
  mkdir -p $HOME/.vagga
  local vagga_settings="$HOME/.vagga/settings.yaml"

  ## Backing up the settings file if it already existed
  mv "$vagga_settings" "${vagga_settings}_backup" >& /dev/null

  ## Configuring an external volume that uses our temp folder
  echo "external-volumes:" > "$vagga_settings"
  echo "  test_vagga: $temp_folder" >> "$vagga_settings"
  
  ## Running vagga
  ## Important: Moving into the folder that is binded inside the container
  cp vagga.yaml "$temp_folder"
  pushd "$temp_folder" > /dev/null
    vagga test
  popd > /dev/null
  
  ## If something was backed up, rename the file back
  mv "${vagga_settings}_backup" "$vagga_settings" >& /dev/null
}

main
```
