### ISSUE TITLE
Running GUI applications in vagga

### ISSUE THREAD

**Issue by gabrielelanaro** [tailhook/vagga#126]
Hi, I would like to know if it is possible and what are the steps to run GUI applications (eg Firefox) in vagga. The idea would be to share the video device and screen with the host system (I'd like to test/develop webgl and opengl applications)

**Comment by tailhook** [comment]
Hi,

Well, you should be able to run GUI applications. There are few issues however

(I) For the X.org socket, you have two options:

1. Your X11 socket is in abstract network namespace. It is in some distributions. And this should make GUI applications work as long as you run `vagga --use-env DISPLAY <command>`
2. You add `/tmp/.X11-unix/..` socket into `external-volumes` setting and mount it inside the container.

(2) Shared memory is separate in a container. Usually, it's okay, but it's probably important for OpenGL. I'm not sure if we can figure out a way to keep shared memory shared with host system

(3) I'm not sure about access to video device(s). It should inherit same capabilities as your user host system, but it looks like that sometimes doesn't work. For example `fuse` doesn't work in user namespaces at all and it can't be fixed AFAIK

(4) Similar to (1) but about dbus socket if you need (I'm not sure about firefox)

Overall GUI applications should work. But I've never tried it myself. And it will probably require some effort to setup this now and to reintegrate some enhancements to the vagga to get this working easily. Would be nice, if you try and give some feedback on this.

**Comment by gabrielelanaro** [comment]
Thanks so much for your answer! I'm trying to setup the GUI integration to know at least how far we can get.

Right now I'm having some problems with creating/mounting the .X11-unix (I'm using the testing automated installer)

This is the one I'm using:
```
containers:
  sphinx:
    setup:
    - !Ubuntu trusty
    - !EnsureDir /tmp/.X11-unix/
#    - !Install [firefox]
#    volumes:
#      /tmp/.X11-unix: !BindRW /volumes/X11

commands:
  bash: !Command
    container: sphinx
    run: /bin/bash
```

If I do vagga bash, I get to a shell but /tmp/.X11-unix is not present. But if I do find the directory in another location:
```
root@gabriele-desktop:/work/# find . -name .X11-unix
./.vagga/.roots/sphinx.4ac63aa4/root/tmp/.X11-unix
```

**Comment by tailhook** [comment]
You can't `EnsureDir` in `/tmp` because the `/tmp` is mounted as tmpfs filesystem on container start. You can use builtin feature of `Tmpfs` by overriding `/tmp` mount:
```
containers:
  sphinx:
    setup:
    - !Ubuntu trusty
    volumes:
      /tmp: !Tmpfs
        size: 100Mi
        mode: 0o1777
        subdirs:
          .X11-unix: # << creates dir for the following mount
      /tmp/.X11-unix: !BindRW /volumes/X11

```

**Comment by tailhook** [comment]
Okay, I was curious enough to get it working with the config above (+ `!Install [firefox]`, and the command line of:
```
vagga -e DISPLAY -e DBUS_SESSION_BUS_ADDRESS -EHOME=/tmp _run sphinx firefox
```

Note that I have dbus (which seems to be needed for firefox) in abstract unix namespace. And I have NixOS on a host system.

If you can run it too, feel free to submit a pull request with an example.

**Comment by gabrielelanaro** [comment]
Thanks again for the tips, that was really helpful. I actually had another problem (firefox couldn't load profile), but got it working in this way (Ubuntu 14.04):

```
vagga firefox
```


```
# vagga.yaml
containers:
  firefox:
    setup:
    - !Ubuntu trusty
    - !Install [firefox]
    volumes:
      /tmp: !Tmpfs
        size: 100Mi
        mode: 0o1777
        subdirs:
          .X11-unix: # << creates dir for the following mount

      /tmp/.X11-unix: !BindRW /volumes/X11

      /root: !Tmpfs
        size: 100Mi
        mode: 0o755

commands:

  firefox: !Command
    container: firefox
    run: firefox

  bash: !Command
    container: firefox
    run: /bin/bash

```

I didn't need to setup DBUS, but I hd to create another tmpfs for home directory (I've seen you equivalently setup the HOME to point to /tmp).

I'll bake a PR later this week.

I'll see if I find any way to make it work for WebGL as well but I don't hold much hope (maybe through chromium/osmesa driver)

**Comment by tailhook** [comment]
Well, I got webgl working both in chrome and firefox, just have to install drivers:
```
containers:
  browser:
    setup:
    - !Ubuntu trusty
    - !UbuntuUniverse
    - !Install [chromium-browser]
    - !Install [firefox, icedtea-plugin]
    - !Install [xserver-xorg-video-intel, mesa-utils, libgl1-mesa-dri]
    - !EnsureDir /root
    volumes:
      /tmp: !Tmpfs
        size: 100Mi
        mode: 0o1777
        subdirs:
          .X11-unix:
      /tmp/.X11-unix: !BindRW /volumes/X11
      /root: !BindRW /work/home

commands:
  firefox: !Command
    container: browser
    run: [firefox]

```

Just for the record: java works too.

**Comment by gabrielelanaro** [comment]
This is really cool! I'll test it with different drivers ( I got nvidia )

**Comment by popravich** [comment]
nice :+1:

**Comment by gabrielelanaro** [comment]
I confirm that the webgl works with nvidia proprietary drivers (that's pretty crazy):

I'll attempt a pull-request in the weekend or early next week with polished examples and doc

```
containers:
  browser:
    setup:
    - !Ubuntu trusty
    - !UbuntuUniverse
    - !Install [binutils, pkg-config, mesa-utils]
    # - !Install [chromium-browser]
    - !Sh sh /work/NVIDIA-Linux-x86_64-331.67.run -a -N --ui=none --no-kernel-module
    - !Sh nvidia-xconfig -a --use-display-device=None --enable-all-gpus --virtual=1280x1024
    # - !Install [nvidia-current]
    - !Install [firefox, icedtea-plugin]
    volumes:
      /tmp: !Tmpfs
        size: 100Mi
        mode: 0o1777
        subdirs:
          .X11-unix:
      /tmp/.X11-unix: !BindRW /volumes/X11
      
      /root: !Tmpfs
        size: 100Mi
        mode: 0o755

commands:
  firefox: !Command
    container: browser
    run: [firefox]

```
