### ISSUE TITLE
Container can be removed/cleaned-up while it is being used

### ISSUE THREAD

**Issue by lilianmoraru** [tailhook/vagga#128]
Let's say we have this config:
```yaml
containers:
  ubuntu:
  ...
  
commands:
  shell: !Command
    description: "Open a shell inside the container"
    container:   ubuntu
    environ:     { PWD: /null }
    run:         bash
    
  build: !Command
    description: "Compile this big project"
    container:   ubuntu
    environ:     { PWD: /null }
    run:         ./ScriptForALongRunningBuild.sh
```

1. You run `vagga build` in one terminal - the build starts
2. You run `vagga shell` in another terminal - you get attached to the container, all keeps working all good
3. You run `exit` from the terminal where you ran `vagga shell` - the build fails because when you ran `exit` vagga cleaned up after itself even though somebody(`vagga build`) was still using the container.
