### ISSUE TITLE
Support for passing an array of containers in SubConfig

### ISSUE THREAD

**Issue by lilianmoraru** [tailhook/vagga#138]
Currently, if you want to use a number of SubConfigs, you have to pass them 1-by-1.
```yaml
containers:
  compilation-tools:
    setup:
    - !Install [gcc, build-essential]
    
  debug-tools:
    setup:
    - !Install [gdb, valgrind]
    
  minimal-build-dep:
    setup:
    - !BuildDeps [cmake]
    
  test-build-dep:
    setup:
    - !BuildDeps [wget, curl, rsync]
    - !SubConfig
      container: minimal-build-dep
      
  set-env:
    setup:
    - !Sh echo "Copying something, somewhere"

  ## Pay attention to this container(ubuntu-test)
  ubuntu-test:
    setup:
    - !Ubuntu trusty
    - !SubConfig
      container: compilation-tools
    - !SubConfig
      container: debug-tools
    - !SubConfig
      container: test-build-dep
    - !SubConfig
      container: set-env
      
    - !Sh echo "Prepare container"
```

Would be nice to have support for indicating the containers in an array.
It could look something like this:
```yaml
containers:
  compilation-tools:
    setup:
    - !Install [gcc, build-essential]
    
  debug-tools:
    setup:
    - !Install [gdb, valgrind]
    
  minimal-build-dep:
    setup:
    - !BuildDeps [cmake]
    
  test-build-dep:
    setup:
    - !BuildDeps [wget, curl, rsync]
    - !SubConfig
      container: [minimal-build-dep]
      
  set-env:
    setup:
    - !Sh echo "Copying something, somewhere"

  ## Pay attention to this container(ubuntu-test)
  ubuntu-test:
    setup:
    - !Ubuntu trusty
    - !SubConfig
      container: [compilation-tools, debug-tools, test-build-dep, set-env]

    - !Sh echo "Prepare container"
    
commands:
  test: !Command
    description: test stuff
    container:   ubuntu-test
    run:         ./test-stuff.sh
```

Note: `container` keyword could probably be changed to `containers` but that would be a breaking change, not sure what should be done about the keyword...

Edit: From the user's perspective, I think changing all the appearances of `container` keyword into `containers` is very simple.

**Comment by tailhook** [comment]
Well, may be you would be better served by yaml anchors:
```
_1: &ctools !Install [gcc, build-essential]
_2: &dtools !Install [gdb, valgrind]
_3: &builddep !BuildDeps [cmake]
containers:
  ubuntu-test:
    setup:
    - !Ubuntu trusty
    - *ctools
    - *dtools
    - *builddep
```
Or you could format the config differently:
```
  ubuntu-test:
    setup:
    - !Ubuntu trusty
    - !SubConfig { container: compilation-tools }
    - !SubConfig { container: debug-tools       }
    - !SubConfig { container: test-build-dep    }
    - !SubConfig { container: set-env           }
```
So it's easy to copy'n'paste, and good to read.

The SubConfig command is complex enough to not make it even more complicated.
