### ISSUE TITLE
Unclear error on wrong config file

### ISSUE THREAD

**Issue by lilianmoraru** [tailhook/vagga#157]
On this config:
```yaml
containers:
  ubuntu:
    setup:
    !Ubuntu trusty
```
Note the missing `-` on `!Ubuntu`. The error will be:
```sh
thread '<main>' panicked at 'not yet implemented', target/.cargo/registry/src/github.com-0a35038f75765ae4/quire-0.1.4/src/decode.rs:263
```

**Comment by tailhook** [comment]
@lilianmoraru which version of vagga do you use? I have the following:
```
Config /home/pc/tmp/vagga.yaml cannot be read: Error parsing config /home/pc/tmp/vagga.yaml: /home/pc/tmp/vagga.yaml:4:5: Parse Error: Expected mapping key or unindent, got Tag
```

Maybe this was fixed by recent upgrade of rust-quire in vagga `0.4.1-95-`

**Comment by lilianmoraru** [comment]
Sorry, my mistake. I removed 2 spaces before posting the issue.
The actual config looks like this:
```yaml
containers:
  ubuntu:
    setup:
      !Ubuntu trusty
```
And it throws the same panic on `v0.4.1` and `v0.4.1-95-gdcfebd4`
