### ISSUE TITLE
tmpfs logs

### ISSUE THREAD

**Issue by lud4ik** [tailhook/vagga#16]
Cfg
```
  ubuntu-asterisk:
    setup:
    - !Container ubuntu
    - !Install [make, wget, ca-certificates, tar]
    - !Sh |
        cd /tmp
        wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
        tar -C /usr/local -xzf go1.4.2.linux-amd64.tar.gz
    - !EnsureDir /var/log/go-asterisk
    environ:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
      GOROOT: /usr/local/go
    volumes:
      /var/log/go-asterisk: !Tmpfs {size: 10Mi}
```
I want to view logs.
Path for log is empty in root container fs while command running. App prints that logs are successfully created. What am I doing wrong?
