### ISSUE TITLE
pip install -e . hangs

### ISSUE THREAD

**Issue by popravich** [tailhook/vagga#186]
When I try to install my project in editable mode both `python setup.py install` / `pip install -e .` goes into `.vagga` directory and hangs forever falking all files in there.
Script to reproduce:
```yaml
containers:
  python:
    setup:
    - !Alpine v3.3
    - !Git
      url: git://github.com/tailhook/injections
      path: /work/
    - !Py3Install [-e, .]
```
`strace` shows the following:
```bash
stat("./.vagga/.mnt/sys/bus/cpu/devices/cpu0/node0/cpu0/node0/cpu0/node0/cpu0/node0/
cpu0/node0/cpu0/node0/cpu0/node0/cpu0/node0/cpu0/node0/cpu0/node0/cpu0/node0/
cpu0/node0/cpu0/node0/cpu0/node0/cpu0/node0/cpu0/node0/cpu0/node0/cpu0/node0/
memory1/node0/memory91/node0/memory100",
 0x7ffcfb38dde8) = -1 ELOOP (Too many levels of symbolic links)
```
