### ISSUE TITLE
Missing `subprocess.run`

### ISSUE THREAD

**Issue by andreaferretti** [tailhook/vagga#187]
Hi, I am trying to use python from a vagga container. Unfortunately, it seems that I am not able to run `subprocess.run`.

I have installed Python with `!Py3Install`, like this

```yaml
containers:
  base:
    setup:
    - !UbuntuRelease { version: 15.04 }
    - !UbuntuUniverse
  wrk:
    setup:
    - !Container base
    - !Install [build-essential, libssl-dev]
    - !Git
      url: https://github.com/wg/wrk.git
      path: /opt/wrk
    - !Sh |
        cd /opt/wrk
        make
    - !PipConfig
      dependencies: true
    - !Py3Install [requests]
```

but when I try `subprocess.run`, I get `AttributeError: 'module' object has no attribute 'run'`
