### ISSUE TITLE
Where does npm install dependencies?

### ISSUE THREAD

**Issue by andreaferretti** [tailhook/vagga#188]
I am trying to use a recent version of node. I have a container with

```yaml
containers:
  node:
    setup:
      - !UbuntuRelease { version: 15.04 }
      - !UbuntuUniverse
      - !BuildDeps [curl]
      - !Install [apt-transport-https, ca-certificates]
      - !Sh |
          curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
      - !UbuntuRepo
        url: https://deb.nodesource.com/node_5.x
        suite: vivid
        components: [main]
      - !Install [nodejs]
      - !NpmConfig
        install_node: false
  koa:
    setup:
      - !Container node
      - !Depends frameworks/koa/package.json
      - !Env
        HOME: /home
      - !NpmConfig
        install_node: false
      - !NpmDependencies
        file: frameworks/koa/package.json
        dev: false
    environ:
      HOME: /home
```

where the file `package.json` has a dependency on `"koa": "^1.2.0"`.

Unfortunately, when I try to run `require('koa')` from a node shell inside the `koa` container, I get `Error: Cannot find module 'koa'`.

Where are npm modules installed by `!NpmDependencies`?

**Comment by andreaferretti** [comment]
Ok, I have solved it myself. Node modules are installed in `/usr/lib/node_modules`. For node to find them, one should set an environment variable `NODE_PATH`, like this

```yaml
  koa:
    setup:
      - !Container node
      - !Depends frameworks/koa/package.json
      - !Env
        HOME: /home
      - !NpmConfig
        install_node: false
      - !NpmDependencies
        file: frameworks/koa/package.json
        dev: false
    environ:
      HOME: /home
      NODE_PATH: /usr/lib/node_modules
```
