### ISSUE TITLE
The su command does not work in containers

### ISSUE THREAD

**Issue by parhamdoustdar** [tailhook/vagga#199]
I was following the [Building a Django project](http://vagga.readthedocs.org/en/latest/examples/tutorials/django.html) tutorial. However, the script when trying to persist the database doesn't work, because running `su` inside the container causes an output like this:

```
su: System error
```

Here is my `vagga.yaml`:

```
containers:
# ...
  postgresql:
    setup:
      - !Ubuntu trusty
      - !Install [postgresql]
      - !EnsureDir /data
      - !EnsureDir /work/.db/data ❶
    environ:
      PGDATA: /data
      PG_PORT: 5433
      PG_DB: test
      PG_USER: vagga
      PG_PASSWORD: vagga
      PG_BIN: /usr/lib/postgresql/9.3/bin
    volumes:
      /data: !BindRW /work/.db/data

commands:
  run: !Supervise
    description: Run the nginx, php and postgresql stack
    mode: stop-on-failure
    children:
      nginx: !Command
        container: nginx
        run: nginx -g "daemon off;"
      php: !Command
        container: php
        environ:
          DATABASE_URL: postgresql://vagga:vagga@127.0.0.1:5433/test
        run: |
            touch /work/.dbcreation # Create lock file
            while [ -f /work/.dbcreation ]; do sleep 0.2; done # Acquire lock
            php-fpm7.0
      init-db: !Command
        container: postgresql
        run: /work/runtime/postgresql/init-db.sh
```

The `runtime/postgresql/init-db.sh` script goes like this:

```
chown postgres:postgres $PGDATA;
if [ -z $(ls -A $PGDATA) ]; then ?
    su postgres -c "$PG_BIN/pg_ctl initdb";
    su postgres -c "echo 'host all all all trust' >> $PGDATA/pg_hba.conf"
    su postgres -c "$PG_BIN/pg_ctl -w -o '-F --port=$PG_PORT -k /tmp' start";
    su postgres -c "$PG_BIN/psql -h 127.0.0.1 -p $PG_PORT -c \"CREATE USER $PG_USER WITH PASSWORD '$PG_PASSWORD';\""
    su postgres -c "$PG_BIN/createdb -h 127.0.0.1 -p $PG_PORT $PG_DB -O $PG_USER";
else ?
    su postgres -c "$PG_BIN/pg_ctl -w -o '-F --port=$PG_PORT -k /tmp' start";
fi
rm /work/.dbcreation # Release lock
sleep infinity
```

And, here is what happens when I connect to the machine and input `sh /work/runtime/postgresql/init-db.sh`:

```
/work/runtime/postgresql/init-db.sh: 2: /work/runtime/postgresql/init-db.sh: ?:
not found
su: System error
su: System error
su: System error
su: System error
su: System error
rm: cannot remove '/work/.dbcreation': No such file or directory
```

Is [this issue](https://github.com/docker/docker/issues/5899) related?
