### ISSUE TITLE
alpine cache doesn’t work when running vagga out of a tmpfs

### ISSUE THREAD

**Issue by dato** [tailhook/vagga#259]
If I'm reading the source correctly, vagga sets up /etc/apk/cache, but it doesn't seem to work. Every time I the container gets rebuilt, all APK packages get downloaded again. Does this need to be manually activated?

I'm using the Vagga 0.5.0 binaries from the download page.

Thanks!

**Comment by tailhook** [comment]
Could you show the build log? I think they are installed every time but not downloaded. On the other hand, indexes are downloaded each time. We don't try to be too smart.

**Comment by dato** [comment]
I was experiencing this when I was using !Alpine (because I couldn't get !Ubuntu to work). I'm experiencing it now that I'm using !Ubuntu.

Here are the two vagga.yaml files that I tested in a clean environment, and their logs.

```
% vagga --version
v0.5.0-154-g5d21335
```

**!Ubuntu**

```yaml
containers:
  test:
    setup:
    - !Depends rebuild.txt
    - !Ubuntu trusty
    - !Install [gcc]

commands:
  gcc: !Command
    container: test
    run: "gcc --version"
```

Log: [alpine caching in vagga (with Ubuntu)](https://gist.github.com/dato/bfcca673e5171b8df2bf0f9735884a74).

**!Alpine**

```yaml
containers:
  test:
    setup:
    - !Depends rebuild.txt
    - !Alpine v3.2
    - !Install [gcc]

commands:
  gcc: !Command
    container: test
    run: "gcc --version"
```

Log: [alpine caching in vagga (with Alpine as distribution)](https://gist.github.com/dato/2b9ab797e7f6fd1f1134e78e78fe4efb).

(I verified there was high bandwidth usage in both runs of the !Alpine version.)

**Comment by lilianmoraru** [comment]
I don't know how `Alpine` behaves but `Ubuntu` definitely reuses the packages if they were downloaded already(although, `apt-get update` is run anyway and the packages get installed again).

**Comment by tailhook** [comment]
I've just run this trough `strace`. apk (alpine package manager) connects exactly once, to fetch index. While fetching index it gets `304 Not Modified` code, so even index doesn't get downloaded. I've also verified that if I remove the cache, installing is much slower.

While we cache as much as we can, we don't have an "offline" mode yet. I mean OS package managers still do some fetches to find out whether the cache is new and similar things. Like in ubuntu's apt-get log you can see which indices are fetched again and which are reused (first is cached, i.e. "hit" the cache, second is refreshed):
```
Hit http://archive.ubuntu.com trusty Release.gpg
Get:2 http://archive.ubuntu.com trusty-updates/main Sources [275 kB]
```

Ah, well, maybe you expect caching work like in docker? I.e. where snapshot of container at intermediate step is cached? We don't do caching of that kind, for few reasons..

**Comment by dato** [comment]
Thanks both for the very detailed explanations.

Ubuntu gets cached properly, I have no complains about it. The following directories get created and populated automatically, and properly mounted on rebuild:

- .vagga/.cache/apt-lists
- .vagga/.cache/apt-cache
- .vagga/.cache/downloads [for the Ubuntu image itself]

The (re-)downloads on rebuild are indeed minimal.

However, the following directory remains empty:

- .vagga/.cache/alpine-cache

both when installing !Ubuntu (when using Alpine for the bootstrap), _or_ when installing !Alpine (I tried with v3.2 and v3.3).

I also tried specifying !CacheDirs `/etc/apk/cache: alpine-cache`, to no avail.

Your comment:

> I've also verified that if I remove the cache, installing is much slower.

makes me thing that in your case the _alpine-cache_ directory gets populated with .apk packages, and that's precisely what doesn't seem to be working for me. It’s empty. The rebuild hits the network every time, por apk packages themself (not just the index).

I'd just like to find out whether I'm doing something wrong.

Thanks again for your responses.

**Comment by tailhook** [comment]
Well, try something along the lines of:
```yaml
containers:
  test:
    setup:
    - !Depends rebuild.txt
    - !Alpine v3.2
    - !Install [gcc]
    - !Sh cat /proc/self/mountinfo
    - !Sh ls -la /etc/apk/cache
```

This will show whether bind mount work and whether apk writes files in right place.
