### ISSUE TITLE
Enable libeatmydata by default

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#262]
I'm testing like this:
```
  ubslow:
    setup:
    - !Ubuntu xenial
    - &pkgs !Install [git, make, ca-certificates, gcc, libssl-dev, lsb-release]

  ubfast:
    setup:
    - !Ubuntu xenial
    - !Install [libeatmydata1]
    - !Env LD_PRELOAD: /usr/lib/x86_64-linux-gnu/libeatmydata.so
    - !Install [git, make, ca-certificates, gcc, libssl-dev, lsb-release]
```

(Just a list of packages I use in one of the projects)

It turns out that installation time is **123 seconds** for ubslow vs **21.7 seconds** for ubfast. I.e. with eatmydata the performance is ubuntu is similar to performance of alpine (sans larger files). Note: measure on a (laptop) SSD.

So I think we should enable libeatmydata by default. This case for xenial ubuntu is easy, because libeatmydata is in the default repository. But for trusty and precise (at least) the package is in `universe`. So we have several options:

1. Enable eatmydata only for xenial by default
2. Enable eatmydata when universe is enabled
3. Always add universe and enable eatmydata on pre-16.04
4. Temporarily enable universe, install eatmydata and disable it afterwards

Any preferences?
