### ISSUE TITLE
!Remove does not remove symbolic links

### ISSUE THREAD

**Issue by Orhideous** [tailhook/vagga#284]
Minimal working `vagga.yaml`
```yaml
containers:
  test:
    setup:
      - !Alpine v3.3
      - !Sh |
          mkdir -p /opt/test_dir
          ln -s /opt/test_dir -T /opt/test_symlink

  inherited:
    setup:
      - !Container test
      - !Remove /opt/test_symlink


commands:
  check: !Command
    container: inherited
    run: ls -hal /opt
```

`vagga check `
```
total 12
drwxrwxr-x    3 root     root        4.0K Jun 17 11:59 .
drwxr-xr-x   19 root     root        4.0K Jun 17 11:59 ..
drwxrwxr-x    2 root     root        4.0K Jun 17 11:59 test_dir
lrwxrwxrwx    1 root     root          13 Jun 17 11:59 test_symlink -> /opt/test_dir
```
As we can see,  `test_symlink` wasn't removed, but it should.
