### ISSUE TITLE
Example crashes with: called Option::unwrap() on a None value

### ISSUE THREAD

**Issue by bascht** [tailhook/vagga#311]
Tried the example from [the docs](http://vagga.readthedocs.io/en/latest/config_overview.html) using Vagga 0.6.1:

```yaml
containers:
  sphinx:
    setup:
    - !Ubuntu xenial
    - !Install [python3-sphinx, make]
commands:
  build-docs: !Command
    description: Build vagga documentation using sphinx
    container: sphinx
    work-dir: docs
    run: [make]
```

```sh
$ env RUST_BACKTRACE=1 vagga build-docs
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326
stack backtrace:
   1:           0x6c62b0 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:           0x6c934b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:           0x6c8fd3 - std::panicking::default_hook::haac48fa641db8fa2
   4:           0x6b494f - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:           0x6b6378 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:           0x6c5791 - rust_begin_unwind
   7:           0x7145bf - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:           0x714898 - core::panicking::panic::hdbcf9a6d5c170498
   9:           0x4d5e1d - vagga::container::uidmap::match_ranges::h4506a9edc578fef5
  10:           0x4dc128 - vagga::container::uidmap::map_users::_$u7b$$u7b$closure$u7d$$u7d$::h5319c4918edf06fc
  11:           0x51b1d4 - _<unshare..Command as launcher..wrap..Wrapper>::map_users_for::hc84c33a94c503317
  12:           0x51ce51 - vagga::launcher::build::build_internal::h255ba2f8f780b75d
  13:           0x518f35 - vagga::launcher::build::build_container::h445d7a3f8e2c4708
  14:           0x50b19a - vagga::launcher::user::run_commands::hbcea7d10c4622895
  15:           0x4f028d - vagga::launcher::run::h325058be5394cec6
  16:           0x402cbd - vagga::main::h6fd685eb63b02a3e
  17:           0x6c8c14 - std::sys_common::unwind::try::try_fn::h09ba69fd13531e58
  18:           0x6c571b - __rust_try
  19:           0x6c881b - std::rt::lang_start::h5b0863080165c75e
```

Let me know if I should supply more details. :)
