### ISSUE TITLE
Repository shortcuts

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#316]
First, we want to have a `!Repo` command which is universal, similar to `!Install`. In its simple form it looks like this:

```yaml
- !Ubuntu xenial
- !Repo universe # == !UbuntuUniverse
- !Repo multiverse
```
Or alpine:
```yaml
- !Alpine v3.4
- !Repo testing
```

In more complex form:
```yaml
- !Ubuntu
- !Repo trusty-updates/universe
# This supersedes:
#- !UbuntuRepo
#  url: http://archive.ubuntu.com
#  suite: trusty-updates
#  components: [universe]
```
Or for alpine:
```yaml
- !Alpine v3.4
- !Repo edge/community
```

The most comprehensive form for ubuntu there is `!UbuntuRepo` for alpine there should be:
```yaml
- !Alpine
- !AlpineRepo
  version: edge
  repo: testing
  alias: newest
- !Install ["python@newest"]
```
(not sure about the exact names of fields)

This merges #220 and #223 (and also consider a related issue #209)

/cc @anti-social
