### ISSUE TITLE
Unable to mount two !Empty volumes

### ISSUE THREAD

**Issue by Orhideous** [tailhook/vagga#328]
```yaml
containers:
  _base-alpine:
    setup:
      - !Alpine v3.4
      - !EnsureDir /config
      - !EnsureDir /log

  dev:
    setup:
      - !Container _base-alpine
    volumes:
      /log: !Empty
      /config: !Empty

commands:
  run: !Command
    container: dev
    run: echo "Hello world"
```
```
vagga --version
v0.6.1-118-gc847847

vagga run
config: /tmp/tst/vagga.yaml:12:19: Parse Error: Null expected, Map found
Config "/tmp/tst/vagga.yaml" cannot be read: Multiple errors in configuration file /tmp/tst/vagga.yaml
```
