### ISSUE TITLE
Persistent volume for database containers

### ISSUE THREAD

**Issue by tokenvolt** [tailhook/vagga#334]
First of all thanks for vagga!

The [example shown in the docs for postgresql container](http://vagga.readthedocs.io/en/latest/examples/db/postgres.html) does not have a persistent volume. Every time I run `psql` command it creates a new volume, which wipes out all the data. Is there a way to make a volume persistent between restarts?

I've already seen an issue https://github.com/tailhook/vagga/issues/204, which I suppose is aimed to achieve this in an elegant way, but it's not in a stable release at the moment, am I right? So, is there a way to implement a persistent volume in any other way?

I'm sorry, if I'm asking silly questions, I'm more a front-end developer, trying to make my life easier with containers =)

**Comment by tailhook** [comment]
Hi,

You should install vagga from `vagga-testing` repository and use `Persistent` volume. Most of our users are running testing repo, because of early features like this. The testing repo is deployed only after automated tests, so it's stable enough for daily usage.

Alternatively, you can create a directory in your project dir and use [!BindRW /work/postgres](http://vagga.readthedocs.io/en/latest/volumes.html#volume-BindRW) volume for it.

Feel free to ask more questions.

**Comment by tokenvolt** [comment]
Thanks for the response, I've tried `!BindRW`, but I'm getting permission denied error while initializing a cluster
```sh
fixing permissions on existing directory /data ... ok
initdb: could not create directory "/data/pg_xlog": Permission denied
initdb: removing contents of data directory "/data"
pg_ctl: database system initialization failed
pg_ctl: directory "/data" is not a database cluster directory
psql: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5433?
createdb: could not connect to database template1: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5433?
```

Here is the full config:
```yaml
containers:
  ubuntu:
    setup:
    - !Ubuntu xenial
    - !Install
      - postgresql-9.5
    - !EnsureDir /data
    - !EnsureDir /work/postgres
    environ:
      PG_PORT: 5433   # Port of host to use
      PG_DB: vagga-test
      PG_USER: vagga
      PG_PASSWORD: vagga
      PGDATA: /data
      PG_BIN: /usr/lib/postgresql/9.5/bin
    volumes:
      /data: !BindRW /work/postgres
commands:
  psql: !Command
    description: Run postgres shell
    container: ubuntu
    # This long script initialized new empty postgres database each time
    # container is run
    run: |
      chown postgres:postgres $PGDATA;
      su postgres -c "$PG_BIN/pg_ctl initdb";
      su postgres -c "$PG_BIN/pg_ctl -w -o '-F --port=$PG_PORT -k /tmp' start";
      su postgres -c "$PG_BIN/psql -h 127.0.0.1 -p $PG_PORT -c \"CREATE USER $PG_USER WITH PASSWORD '$PG_PASSWORD';\""
      su postgres -c "$PG_BIN/createdb -h 127.0.0.1 -p $PG_PORT $PG_DB -O $PG_USER";
      sleep infinity
```
BTW I'm using vagrant on OS X with a vagrant-vagga plugin.
