### ISSUE TITLE
Alternative Command-line interface for supervise

### ISSUE THREAD

**Issue by livioribeiro** [tailhook/vagga#341]
In #338 was proposed passing params to commands in `!Supervise` via environments vars. I want to propose an alternative using parameters prefixed with the name of the child command they are meant to be passed to. Let's take the example at the first proposal:

```yaml
commands:
  tests: !Supervise
    description: Run test suite
    children:
      tests: !Command
        container: py
        run:
          - "py.test"
      redis: !Command
        container: redis
        run:
          - "redis-server"
          - "--daemonize"
          - "no"
```

The command would be called like this:

    $ vagga tests --tests_redis-port $PORT --redis_port $PORT

The prefix of the parameters would be stripped and passed to its respective command. Parameters with only the name of the child command would be passed as positional arguments.

This approach has 2 major drawbacks, however:

* We lose the benefits of using docopt 
* It adds complexity to the caller
