### ISSUE TITLE
!AlpineRepo doesn't work for inherited images

### ISSUE THREAD

**Issue by Orhideous** [tailhook/vagga#342]
**vagga.yaml**
```
containers:
  _base_alpine:
    setup:
    - !Alpine v3.4
    - !EnsureDir /config
    - !Sh "chmod +r /bin/bbsuid"
    - !AlpineRepo {branch: edge, repo: testing, tag: testing}

  inherited:
    setup:
    - !Container _base_alpine
    - !Install [php5-redis@testing]

  full:
    setup:
    - !Alpine v3.4
    - !EnsureDir /config
    - !Sh "chmod +r /bin/bbsuid"
    - !AlpineRepo {branch: edge, repo: testing, tag: testing}
    - !Install [php5-redis@testing]
```
Attempt to build inherited container fails:
```
akushnir@akushnir:/tmp/alp$ vagga _build inherited 
(1/1) Installing alpine-keys (1.1-r0)
OK: 0 MiB in 1 packages
fetch http://mirrors.gigenet.com/alpinelinux/v3.4/main/x86_64/APKINDEX.tar.gz
(1/16) Installing musl (1.1.14-r11)
(2/16) Installing busybox (1.24.2-r11)
Executing busybox-1.24.2-r11.post-install
(3/16) Installing alpine-baselayout (3.0.3-r0)
Executing alpine-baselayout-3.0.3-r0.pre-install
Executing alpine-baselayout-3.0.3-r0.post-install
(4/16) Installing openrc (0.21-r2)
Executing openrc-0.21-r2.post-install
(5/16) Installing alpine-conf (3.4.1-r2)
(6/16) Installing zlib (1.2.8-r2)
(7/16) Installing libcrypto1.0 (1.0.2h-r1)
(8/16) Installing libssl1.0 (1.0.2h-r1)
(9/16) Installing apk-tools (2.6.7-r0)
(10/16) Installing busybox-suid (1.24.2-r11)
(11/16) Installing busybox-initscripts (3.0-r3)
Executing busybox-initscripts-3.0-r3.post-install
(12/16) Installing scanelf (1.1.6-r0)
(13/16) Installing musl-utils (1.1.14-r11)
(14/16) Installing libc-utils (0.7-r0)
(15/16) Installing alpine-keys (1.1-r0)
(16/16) Installing alpine-base (3.4.3-r0)
Executing busybox-1.24.2-r11.trigger
OK: 7 MiB in 16 packages
+ chmod +r /bin/bbsuid
WARNING: Ignoring APKINDEX.98197ebc.tar.gz: No such file or directory
OK: 7 MiB in 16 packages
OK: 0 MiB in 1 packages
fetch http://repository.fit.cvut.cz/mirrors/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
OK: 7 MiB in 16 packages
fetch http://repository.fit.cvut.cz/mirrors/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
WARNING: The repository tag for world dependency 'php5-redis@testing' does not exist
ERROR: Not committing changes due to missing repository tags. Use --force to override.
ERROR:vagga::builder: Error building container "inherited": step Install(["php5-redis@testing"]) failed: Apk exited with status: exited with code -1
ERROR:vagga::wrapper: Error executing _build: Builder exited with code 1
Command <Command "/proc/self/exe" ("vagga_wrapper") "_build" "inherited"; environ: {"TERM"="xterm-256color","RUST_LOG"="warn","_VAGGA_HOME"="/home/akushnir",}; uid_map=[UidMap { inside_uid: 0, outside_uid: 1001, count: 1 }, UidMap { inside_uid: 1, outside_uid: 165536, count: 65535 }]; gid_map=[GidMap { inside_gid: 0, outside_gid: 1001, count: 1 }, GidMap { inside_gid: 1, outside_gid: 165536, count: 65535 }]> exited with code 124
```
But in simple case without inheritance build finishes successfully
```
akushnir@akushnir:/tmp/alp$ vagga _build full
(1/1) Installing alpine-keys (1.1-r0)
OK: 0 MiB in 1 packages
fetch http://alpine.mirror.far.fi/v3.4/main/x86_64/APKINDEX.tar.gz
(1/16) Installing musl (1.1.14-r11)
(2/16) Installing busybox (1.24.2-r11)
Executing busybox-1.24.2-r11.post-install
(3/16) Installing alpine-baselayout (3.0.3-r0)
Executing alpine-baselayout-3.0.3-r0.pre-install
Executing alpine-baselayout-3.0.3-r0.post-install
(4/16) Installing openrc (0.21-r2)
Executing openrc-0.21-r2.post-install
(5/16) Installing alpine-conf (3.4.1-r2)
(6/16) Installing zlib (1.2.8-r2)
(7/16) Installing libcrypto1.0 (1.0.2h-r1)
(8/16) Installing libssl1.0 (1.0.2h-r1)
(9/16) Installing apk-tools (2.6.7-r0)
(10/16) Installing busybox-suid (1.24.2-r11)
(11/16) Installing busybox-initscripts (3.0-r3)
Executing busybox-initscripts-3.0-r3.post-install
(12/16) Installing scanelf (1.1.6-r0)
(13/16) Installing musl-utils (1.1.14-r11)
(14/16) Installing libc-utils (0.7-r0)
(15/16) Installing alpine-keys (1.1-r0)
(16/16) Installing alpine-base (3.4.3-r0)
Executing busybox-1.24.2-r11.trigger
OK: 7 MiB in 16 packages
+ chmod +r /bin/bbsuid
fetch http://alpine.mirror.far.fi/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://alpine.mirror.far.fi/edge/testing/x86_64/APKINDEX.tar.gz
(1/1) Installing php5-redis@testing (2.2.8-r0)
OK: 7 MiB in 17 packages
OK: 7 MiB in 17 packages
```
