### ISSUE TITLE
Error creating dir: couldn't stat path 

### ISSUE THREAD

**Issue by lud4ik** [tailhook/vagga#35]
Cfg
```
# http://vagga.readthedocs.org/en/latest/

commands:
  rabbit: !Command
    description: Rabbitmq for statistic of smart delivery
    container: ubuntu-rabbitmq
    run: |
        sudo /etc/init.d/rabbitmq-server start

containers:

  ubuntu:
    setup:
    - !Ubuntu trusty
    - !UbuntuUniverse ~
    - !EnsureDir /var/lib/apt/mirrors

  ubuntu-rabbitmq:
    setup:
    - !Container ubuntu
    - !Install [ca-certificates, wget, erlang-nox]
    - !EnsureDir /var/run/rabbitmq
    - !EnsureDir /var/lib/rabbitmq
    - !Sh |
        ln -s -f /bin/true /usr/bin/chfn
        cd /tmp
        wget https://www.rabbitmq.com/releases/rabbitmq-server/v3.5.3/rabbitmq-server_3.5.3-1_all.deb
        sudo dpkg -i rabbitmq-server_3.5.3-1_all.deb
        sudo rabbitmq-plugins enable rabbitmq_management
    volumes:
      /var/run/rabbitmq: !Tmpfs {size: 25Mi}
      /var/lib/rabbitmq: !Tmpfs {size: 25Mi}
```

Error
```
... (ok)
Setting up erlang-parsetools (1:16.b.3-dfsg-1ubuntu2.1) ...
Setting up erlang-percept (1:16.b.3-dfsg-1ubuntu2.1) ...
Setting up erlang-ssh (1:16.b.3-dfsg-1ubuntu2.1) ...
Setting up erlang-webtool (1:16.b.3-dfsg-1ubuntu2.1) ...
Setting up erlang-tools (1:16.b.3-dfsg-1ubuntu2.1) ...
Setting up erlang-nox (1:16.b.3-dfsg-1ubuntu2.1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Processing triggers for ca-certificates (20141019ubuntu0.14.04.1) ...
Updating certificates in /etc/ssl/certs... 173 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
ERROR:main: Error building container "ubuntu-rabbitmq": Error creating dir: couldn't stat path (no such file or directory (No such file or directory); path=/vagga/root/var/run)
ERROR:main: Error executing _build: Builder exited with code 1
Build returned 124
```

**Comment by tailhook** [comment]
I guess `!EnsureDir` is not recursive, you may need:
```
- !EnsureDir /var
- !EnsureDir /var/run
- !EnsureDir /var/run/rabbitmq
```

**Comment by lud4ik** [comment]
Seem to work
```
# http://vagga.readthedocs.org/en/latest/

commands:

  rabbit: !Command
    description: Rabbitmq server for chatapp
    container: ubuntu-rabbitmq
    run: |
        sudo service rabbitmq-server start

containers:

  ubuntu:
    setup:
    - !Ubuntu trusty
    - !UbuntuUniverse ~
    - !EnsureDir /var/lib/apt/mirrors

  ubuntu-rabbitmq:
    setup:
    - !Container ubuntu
    - !Install [ca-certificates, wget, erlang-nox]
    - !Sh |
        cd /tmp
        sudo mkdir /var/lib/rabbitmq
        sudo mkdir /var/run/rabbitmq
        wget https://www.rabbitmq.com/releases/rabbitmq-server/v3.5.3/rabbitmq-server_3.5.3-1_all.deb
        sudo dpkg -i rabbitmq-server_3.5.3-1_all.deb
        sudo rabbitmq-plugins enable rabbitmq_management
```
But smth is wrong. How can I check if process started? With nsenter?
