### ISSUE TITLE
Is `write-mode` disabled?

### ISSUE THREAD

**Issue by piranna** [tailhook/vagga#367]
I have created a data-only container to be used as a volume, but `vagga` mounts it as read-only (and the same for `/`). Reading on the docs it seems would be possible to write it by using `write-mode: transient-hard-link-copy`, but the point is that's being ignored and in fact I have search on the `vagga` source code and only references are in the docs, not in the code itself. Has been this option get disabled? If not, how could I use it? My `vagga.yaml` file is like:

```yaml
containers:
  bootfs:
    auto-clean: true
    hosts-file-path: null
    resolv-conf-path: null
    setup:
    - !Tar
      url: ./out/latest/barebones
    - !Tar
      url: ./out/latest/initramfs
  usersfs:
    data-dirs: [/nodeos, /root]
    setup:
    - !Tar
      url: ./out/latest/usersfs

commands:
  run: !Command
    description: Start NodeOS
    container: bootfs
    volumes:
      /tmp: !Container usersfs
    environ:
#       PWD: /
#      root: ''
      root: 'container'
#     pid1mode: exec
    run: [/init]
    write-mode: transient-hard-link-copy
```

Also, is there any option to make a volume "full read-only", writting directly over the files instead of doing a copy? I know I could be able to use a external folder and the `BindRW` command, but since I'm filling it from a tarfile I wanted to isolate the "filesystem" as a black box...

**Comment by anti-social** [comment]
I think you can use `!Snapshot` volume with container option: http://vagga.readthedocs.io/en/latest/volumes.html#volume-Snapshot

The only change you should make is to move `/nodeos` and `/root` directories into `/tmp`.

**Comment by anti-social** [comment]
Oh, sorry, you cannot move directories into `/tmp` cause it is on tmpfs.

**Comment by anti-social** [comment]
Possibly we might add an option like `container-path` for `!Snapshot` volume to have a possibility to specify different source path.

**Comment by anti-social** [comment]
Also `write-mode: transient-hard-link-copy` works but it creates hard links only for root container not for volumes. Try to search `write_mode`, for example: https://github.com/tailhook/vagga/blob/master/src/wrapper/commandline.rs#L64

**Comment by piranna** [comment]
> I think you can use !Snapshot volume with container option: http://vagga.readthedocs.io/en/latest/volumes.html#volume-Snapshot

It's an interesting option, but that would not allow to store the changes. It would be useful for the `/` dir, but seems it's not possible at this moment :-/


> Also write-mode: transient-hard-link-copy works but it creates hard links only for root container not for volumes. Try to search write_mode, for example: https://github.com/tailhook/vagga/blob/master/src/wrapper/commandline.rs#L64

My fault, I was looking for `write-mode`, not `write_mode`.

So, could there be any option to mount a volume as read-write beyond `BindRW`?

**Comment by anti-social** [comment]
There is `!Persistent` volume type which stores data inside `.vagga/.volumes` direcotory. It has `init-command` option to specify a command that can initialize data for the volume.

**Comment by piranna** [comment]
> There is !Persistent volume type which stores data inside .vagga/.volumes direcotory. It has init-command option to specify a command that can initialize data for the volume.

It's the first thing I tried, but for some reason it didn't worked for me with the `!Tar` command :-/

**Comment by anti-social** [comment]
There is no way to use build step commands for defining `!Command`'s `run` option. Use shell commands: `wget` & `tar`. Think something like this should work:

```
containers:
  busybox:
    setup:
    - !Alpine v3.4

commands:
  _init-usersfs:
    container: busybox
    volumes:
      /tmp: !Persistent {name: "usersfs"}
    run: |
        tar -xzf /work/out/latest/usersfs -C /tmp

  run: !Command
    description: Start NodeOS
    container: bootfs
    volumes:
      /tmp: !Persistent
        name: "usersfs"
        init-command: _init-userfs
    run: [/init]
```

**Comment by tailhook** [comment]
@piranna 

1. You can't un-`!Tar` to a volume. You can't write to a volume in build process.
2. We don't have a concept of "data container" in the sense of Docker has because they are not containers they are actually volumes. So we have volumes concept and `!Persistent` and `!Shapshot` volume types are our way to have a volumes managed by vagga
3. `Persistent` volume is created empty, we have not implemented `seed` parameter (but it's part of #204)

In case you want to fill persistent volume you need to create another command and put it into prerequisites,
like this:

```yaml
containers:
  mycontainer:
    setup: ...
    volumes:
      /userfs/mountpoint: !Persistent
        name: userfs
        init-command: _unpack
commands:
  _unpack: !Command
    container: mycontainer
    run: |
      tar -xzf archive.tar.gz -C /userfs/mountpoint

  run: !Command
    description: Start NodeOS
    container: mycontainer
    run: [/init]
```

While volume will only initialize once, you may put `_unpack` into prerequisites to `run` and add more comprehensive script there. You can also unpack archive at container build and only copy/rsync files at volume initialization.
