### ISSUE TITLE
`faketime` utility fails when building container on old ubuntu host system

### ISSUE THREAD

**Issue by anti-social** [tailhook/vagga#370]
Host system: Ubuntu trusty.

`vagga.yaml`:
```
containers:
  faketime:
    setup:
    - !Ubuntu xenial
    - !UbuntuUniverse
    - !Install [faketime]
    - !Sh faketime @1 date
```

```
$ vagga _build faketime
...
+ faketime @1 date
sem_open: Permission denied
```

We need to mount `tmpfs` into `/run` and create `/run/shm` folder.
