### ISSUE TITLE
Unzip command fails to unpack packages with missing intermediate directories

### ISSUE THREAD

**Issue by Orhideous** [tailhook/vagga#397]
Configuration to reproduce:
```yaml
test:
  setup:
  - !Alpine v3.4
  - !Unzip
    url: http://archive.cloudera.com/beta/livy/livy-server-0.3.0.zip
    path: /opt
```

`vagga _build test`

```
ERROR:vagga::builder: Error building container "test": step Unzip { url: "http://archive.cloudera.com/beta/livy/livy-server-0.3.0.zip", sha256: None, path: "/opt", subdir: "" } failed: Error creating file: No such file or directory (os error 2)
ERROR:vagga::wrapper: Error executing _build: Builder exited with code 1
```

Maybe similar to #283
