### ISSUE TITLE
Improve dependency tracking with inheritance

### ISSUE THREAD

**Issue by webknjaz** [tailhook/vagga#420]
Given the following configuration and all the containers already built:

```yaml
containers:
  app:
    setup:
      ...
      - !Depends setup.py
      ...
  test:
    setup:
      - !Container app
      ...
      - !Depends .pre-commit-config.yaml
      ...
```

If `setup.py` has changed and we run command against `test` container `vagga` doesn't pick up this change.
I didn't dig into the code, but it seems that it only checks `!Depends` directive of `test` container.

Ideally, it should recursively detect all dependencies and rebuild both containers.

The workaround could be repeated dependency in `test` container declaration with probably yaml anchor for avoiding at least value duplication.

**Comment by anti-social** [comment]
What kind of inheritance do you use? 

```
containers:
  test1:
    setup:
    - !Alpine v3.5
    - !Depends test1.txt

  test2:
    setup:
    - !Container test1
    - !Depends test2.txt
```

When I change `test1.txt` file vagga rebuilds both containers.
