### ISSUE TITLE
Automatically detect `.so` needed

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#439]
# Motivation

We want to build minimal containers. Currently, to make a minimal container for dynamically linked executable, we need config like this:

```yaml
containers:
  build-swindon:
    setup:
    # .. build process
    - !Sh |
        mkdir -p /dist/bin /dist/lib64\
          /dist/usr/lib/x86_64-linux-gnu \
          /dist/lib/x86_64-linux-gnu
        cp /lib64/ld-linux-x86-64.so.2 /dist/lib64

        ldd target/release/swindon \
        | awk '/=> \//{print $3}' \
        | xargs -I{} -n1 cp '{}' /dist/usr/lib/x86_64-linux-gnu

        # dynamically loaded stdlib plugins
        cp \
          /lib/x86_64-linux-gnu/libresolv.so.2 \
          /lib/x86_64-linux-gnu/libnss_dns.so.2 \
          /dist/lib/x86_64-linux-gnu

        cp target/release/swindon /dist/bin/swindon
  swindon-deploy:
    setup:
    - !Build
      container: build-swindon
      source: /dist
      path: /
```

There are basically two things here:
1. Finding libraries by `ldd`
2. Copying known libraries for name resolution (a/k/a nss, a/k/a DNS)

# Option 1

1. We should add `rules` option for build, like for `Copy` and `Depends`
2. We should add a special rule:

```
  swindon-deploy:
    setup:
    - !Build
      container: build-swindon
      rules:
      - /usr/bin/swindon#so-dependencies
```
Or:
```
  swindon-deploy:
    setup:
    - !Copy
      source: target/release/swindon
      rules:
      - /usr/bin/swindon#so-dependencies
```

Pros:
1. Easily supports multiple binaries
2. Integrates with `Depends`, `Copy` and `Build`

Cons:
1. Complexity of `rules`
2. Unclear what base paths are for `Copy` and `Depends`
3. Unclear now to fix "nss problem" (just document needed rules?)

# Option 2

```yaml
- !LddCopy
  binaries:
  - /usr/bin/swindon
```

Actually not show where it will copy from and to, so listing just for comprehensiveness and brainstorming.

# Option 3

```yaml
    - !Build
      container: build-swindon
      source-executables: /dist
      copy-nss: true  # detect and copy needed nss files for libc
      path: /
```

Pros:
1. Quite simple

Cons:
1. Unclear how to copy data files along with executables and so

# Notes

It looks like possible to use `elf` crate or [`static-ldd`](https://github.com/jameysharp/static-ldd) to find out dependencies

Another [motivating implementation](https://hackernoon.com/how-to-build-a-tiny-httpd-container-ae622c37db39) by oracle.

Additionally, it's a good idea to make tutorials for common setup with rust, go as major use cases and evaluate scripting languages too.

/cc @anti-social

**Comment by anti-social** [comment]
I definitely don't like special syntax for rules. Think there should be separate command for that task.

**Comment by tailhook** [comment]
> I definitely don't like special syntax for rules. Think there should be separate command for that task.

I don't get it. What do you propose "Option 2" from above? I don't see how to make sane semantics for the command.

**Comment by anti-social** [comment]
Yes, I propose "Option 2":
```
- !LddCopy
  path: /dist
  binaries:
  - /usr/bin/swindon
```
Should copy `/usr/bin/swindon` into `/dist/usr/bin/swindon` and all the libraries into `/dist/usr/lib/x86_64-linux-gnu`

Possibly we could make configuration more detailed:
```
- !LddCopy
  lib_path: /dist
  binaries:
  - 
    source: /usr/bin/swindon
    path: /dist/bin/swindon
```
