### ISSUE TITLE
GitDescribe command

### ISSUE THREAD

**Issue by anti-social** [tailhook/vagga#441]
It should be useful when building deploy containers.

Full version of the command:

```yaml
- !GitDescribe
  repo: /work
  path: /app_version
```

Also there can be short version:

```yaml
- !GitDescribe /app_version
```

Whether we need `git describe` options? If so what options should be implemented?
