### ISSUE TITLE
In container for Rust development, cargo fails to create .cargo-index-lock in read only /root

### ISSUE THREAD

**Issue by bootchk** [tailhook/vagga#454]
I am creating a vagga script for a Rust cross compiling environment, using xargo.  Within that container, the command  "xargo build --example hello" yields:

```
error: failed to open: /root/.cargo/registry/index/github.com-1ecc6299db9ec823/.cargo-index-lock

Caused by:
  Read-only file system (os error 30)
```

A fix seems to be (from another issue's answer):

      - !Sh "sed -i '/^root/{s@/root@/work/.home@;}' /etc/passwd"

I am just documenting one solution.  Maybe there is a better one, or there is an existing example vagga script for the purpose of Rust development and Rust cross development?

Also, I don't understand why cargo (or xargo?) would write to /root.

**Comment by tailhook** [comment]
Usually it's enough to put `HOME: /work/.home` or even `CARGO_HOME: /work/.home` into container's `environ` (we start from the clean one, so it gets HOME from /etc/passwd). Maybe you need `XARGO_HOME`.

Also usually I put `CARGO_HOME` in `/work/target` so fewer directories to add into `.gitignore` (`target` is where build artifacts put into by cargo), or on a `!Persistent` volume (better for CI, if the latter does `git clean -fdx` on each build).

**Comment by bootchk** [comment]
I am still having trouble using rustup in a vagga script.  Do you have an example script that installs rustup in a container?

Is the environ clause  in effect when setup clause runs?  Or do I need to define CARGO_HOME within the setup clause preceding invocation of rustup.rs?

**Comment by tailhook** [comment]
No, I don't use rustup in container, usually I just use a [binary package](https://github.com/tailhook/vagga/blob/master/vagga.yaml#L23-L25), so I don't have an example.

The env issue is following. If you run rustup as part of the build process, you should use `!Env`, like this:
```
- !Env { CARGO_HOME: /somewhere }
- !Sh rustup ...
```
(By default during the build process the `HOME` is `/tmp`, so that commands which put intermediate artifacts in home work, but installations into `$HOME/.../bin` are useless)

If you use it in a command, you can put environment either in container or in command:
```
containers:
  rustup:
    setup:
    ...
    environ:
      CARGO_HOME: /somewhere

commands:
  rustup: !Command
    container: rustup
    run: [rustup]
    environ:
      CARGO_HOME: /somewhere
```
(I'm duplicating it the last example, you should choose one of the places, depending on your convenience, usually putting env in container is fine)

If that doesn't work, please show the example config you're trying, this way it would be easier for me to help.

**Comment by bootchk** [comment]
Thanks, indeed I was confused about the env of the build versus the env of the built container.  Also, I was confused about whether a built sub container inherits the env of its super container (as you say in the documentation, it doesn't, you must repeat the environ clause.)

This seems to work

```
  rustup:
  
    environ:
      PATH: "/work/.home/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      HOME: /work/.home
      RUSTUP_HOME: /work/.home/.cargo
      
    setup:
    - !Container base
  
    - !Env
      RUST_TARGET_PATH: /work/.home
      RUSTUP_HOME: /work/.home/.cargo
      CARGO_HOME: /work/.home/.cargo
      
    - !Download
      url: https://sh.rustup.rs
      path: /work/rustup.rs
      mode: 0o744
      
    - !Sh "/work/rustup.rs -y --default-toolchain nightly"
```
