### ISSUE TITLE
Installed package is erroneously removed at the end of container build

### ISSUE THREAD

**Issue by bitc** [tailhook/vagga#46]
With this `vagga.yaml`:

``` yaml
containers:
  build:
    setup:
    - !Ubuntu trusty
    - !UbuntuUniverse

    - !BuildDeps [zlib1g-dev]

    - !Install [libpq-dev]
```

The `libpq-dev` package is removed and cannot be found in the container:

    $ vagga _run build ls /usr/lib/libpq.a
    ... snip ...
    Setting up libpq-dev (9.3.9-0ubuntu0.14.04) ...
    ... snip ...
    Removing libpq-dev (9.3.9-0ubuntu0.14.04) ...
    ... snip ...
    /bin/ls: cannot access /usr/lib/libpq.a: No such file or directory

If I remove the line with `zlib1g-dev`, or change it to `!Install` instead of `!BuildDeps` then everything works fine:

    $ vagga _run build ls /usr/lib/libpq.a
    ... snip ...
    /usr/lib/libpq.a
