### ISSUE TITLE
Linking command into Supervise children

### ISSUE THREAD

**Issue by anti-social** [tailhook/vagga#466]
Suppose we have a mixin with some commands. And in main `vagga.yaml` we have `Supervise` command in which we want to use command from mixin. Anchors also don't work between different files. So at the moment the only way is to move such command into main vagga config.

So I suggest to implement one more tag for supervised child: `LinkCommand`. Below shows how it might look like:

`postgres.yaml`:
```
containers:
  postgres:
    setup:
    ...

commands:
  postgres: !Command
    container: postgres
    run: |
      ...
```

`vagga.yaml`:
```
mixins: 
- postgres.yaml

containers:
...

commands:
  test: !Supervise
  children:
    postgres: !LinkCommand postgres
    ...
```
