### ISSUE TITLE
Anchors and aliases parsing

### ISSUE THREAD

**Issue by kvasnevskyi** [tailhook/vagga#499]
Not valid parsing of anchors and aliases.

[Demo](https://asciinema.org/a/0Kec20vum1UZRA14G1IPfC4lQ)

The code of this kind works correctly, although it should not.

```
catcontainers:                                                                                                                                                                                                                                
    base:                                                                                                                                                                                                                                     
        setup:                                                                                                                                                                                                                                
            - !Alpine v3.8                                                                                                                                                                                                                    
                                                                                                                                                                                                                                              
commands:                                                                                                                                                                                                                                     
    cat: &cat !Command                                                                                                                                                                                                                        
        container: base                                                                                                                                                                                                                       
        run: cat vagga.yaml                                                                                                                                                                                                                   
                                                                                                                                                                                                                                              
    ls: &ls !Command                                                                                                                                                                                                                          
        container: base                                                                                                                                                                                                                       
        run: ls /work                                                                                                                                                                                                                         
                                                                                                                                                                                                                                              
    all: !Supervise                                                                                                                                                                                                                           
        children:                                                                                                                                                                                                                             
            cat: !Command                                                                                                                                                                                                                     
                *cat                                                                                                                                                                                                                          
            ls: !Command                                                                                                                                                                                                                      
                *ls     
```
