### ISSUE TITLE
Ubuntu 20.4 fossa fails to install with 404 on repository

### ISSUE THREAD

**Issue by bootchk** [tailhook/vagga#537]
My vagga script starts with:

 ```
containers:
 # basic OS with dev (compiling)
  baseOS:
    setup:
    # 18.10
    # - !Ubuntu cosmic
    # 19.04
    # - !Ubuntu disco
    # ubuntu 19.10, which has meson 51
    - !Ubuntu eoan
    # 20.4 LTS
    #- !Ubuntu fossa
```

If you change the comments so that it tries to install Ubuntu 20.4, it fails.  A prefix of the log:

(1/1) Installing alpine-keys (2.1-r1)
OK: 0 MiB in 1 packages
(1/6) Installing musl (1.1.15-r8)
(2/6) Installing busybox (1.25.1-r2)
Executing busybox-1.25.1-r2.post-install
(3/6) Installing libressl2.4-libcrypto (2.4.4-r0)
(4/6) Installing ca-certificates (20161130-r1)
(5/6) Installing libressl2.4-libssl (2.4.4-r0)
(6/6) Installing wget (1.18-r4)
Executing busybox-1.25.1-r2.trigger
Executing ca-certificates-20161130-r1.trigger
OK: 4 MiB in 7 packages
ERROR: could not open HSTS store. HSTS will be disabled.
--2020-06-14 11:48:12--  https://partner-images.canonical.com/core/fossa/current/ubuntu-fossa-core-cloudimg-amd64-root.tar.gz
Resolving partner-images.canonical.com... 91.189.88.147
Connecting to partner-images.canonical.com|91.189.88.147|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-06-14 11:48:12 ERROR 404: Not Found.

ERROR 2020-06-14T11:48:12Z: vagga::capsule::download: Error downloading "https://partner-images.canonical.com/core/fossa/current/ubuntu-fossa-core-cloudimg-amd64-root.tar.gz", wget Exited(8)
