### ISSUE TITLE
Writeable filesystem option

### ISSUE THREAD

**Issue by kismet010** [tailhook/vagga#55]
There's some use cases where a program needs to write to, i.e., /etc
In my case, after installing apache and copying a virtualhost I need to restart the service, but it fails trying to write to /var/logs.
How can we achieve this?

BTW, thanks a lot for making this :)

**Comment by tailhook** [comment]
There are currently three options:

1. Tmpfs mount, that's what I'm using for logs most of the time, because it cleans up on restart:
    ```
    containers:
      apache:
        setup:
         ...
        - !EnsureDir /var/logs
        volumes:
            /var/logs: !Tmpfs { size: 1Mi } 
    ```

2. Bind directory from project dir (you need to create `tmp/logs` directory under you workdir manually):
    ```
    volumes:
        /var/logs: !BindRW /work/tmp/logs 
    ```

3. The `write-mode: transient-hard-link-copy` in command definition. It's mostly used for building packages. It's probably not what you want, just list here for completeness.

http://vagga.readthedocs.org/en/latest/volumes.html
