### ISSUE TITLE
Mounting external directories using command line option

### ISSUE THREAD

**Issue by anti-social** [tailhook/vagga#574]
```bash
vagga --mount-bind $HOME/.cargo:/work/target/.cargo run
```

At the moment we can emulate such a behavior:

`vagga.yaml`:

```yaml
commands:
  run-ci: !Command
   <<: *run-cmd
    volumes:
      /work/target/.cargo: !BindRW /volumes/cargo
```

```bash
export VAGGA_SETTINGS="
external-volumes:
  cargo: $HOME/.cargo"
vagga run-ci
```

Think it is too complex to be really useful.

Possible options:
- `--mount-bind`
- `--mount-bind-ro`
- `--mount-tmpfs`
- `--mount-snapshot`

Either we can have a single `--mount` option and pass mount type encoded inside an argument.
