### ISSUE TITLE
feature request: vagga.yaml anchors or reusable blocks

### ISSUE THREAD

**Issue by popravich** [tailhook/vagga#73]
It would've been nice to have YAML anchors support or some other kind of "reusable blocks / templates" support.
My story:
Say, I have supervising command named `test` in vagga.yaml which run 3 sub-command: `redis-server`, `postgres-server` and `run-tests`.
Next I want to add `shell` supervising command with almost the same sub-commands but instead of `run-tests` to start `bash` to be able to run `ipython` or to manually run tests or whatever.

Currently I need to copy-paste big parts of `test` command and it does make me sad)

One elegant solution is to make `!Supervise` command look through other commands and reuse them, eg:
```yaml
commands:
  redis-server: !Command
    description: start redis server
    container: ubuntu
    run: redis-server --deamonize no
 test: !Supervise
   children:
     redis: !Command redis-server
     test: !Command
        container: ubuntu
        run: run-my-redis-driver-tests
```

**Comment by sashasimkin** [comment]
+1

**Comment by tailhook** [comment]
Looks like it works. If there are any further issues with this, feel free to open another issue (better in http://github.com/tailhook/rust-quire)

**Comment by jnv** [comment]
For future reference, the example above will work with YAML aliases like this:

```
commands:
  redis-server: &redis-server !Command
    description: start redis server
    container: ubuntu
    run: redis-server --daemonize no
 test: !Supervise
   children:
     redis: *redis-server
     test: !Command
        container: ubuntu
        run: run-my-redis-driver-tests
```
