### ISSUE TITLE
"thread '<main>' has overflowed its stack"

### ISSUE THREAD

**Issue by popravich** [tailhook/vagga#94]
Most of time container build fails with following error (but sometimes it builds):
```
thread '<main>' has overflowed its stack
ERROR:vagga::wrapper: Error executing _build: Builder killed by signal SIGILL[4] (core dumped)
```

Vagga version `v0.4.0-10-g933693c`
`vagga.yaml`:
```yaml
containers:
  ubuntu:
    setup:
    - !UbuntuRelease { version: 15.04 }
    - !PipConfig { dependencies: true }
    - !Py3Requirements "requirements.txt"

  test:
    setup:
    - !Container ubuntu
    - !Py3Install [coverage]
```
`requirements.txt`:
```
Flask==0.10.1
```

**Comment by popravich** [comment]
So we know it caused by recursion on files copy and temp fix released I have an update with
a thing that loves deep directories)
```yaml
containers:
  ubuntu:
    setup:
    - !UbuntuRelease { version: 15.04 }
    - !NpmInstall
      - gulp-imagemin

  test:
    setup:
    - !Container ubuntu
```

vagga is latest from testing repo (`v0.4.0-20-gf92e92a`)
